# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TYLM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SnapKit'
# 轮播图
pod 'SDCycleScrollView'

pod 'HandyJSON'
pod 'SwiftyJSON'
pod 'Alamofire'
pod 'Kingfisher'
pod 'IQKeyboardManagerSwift'
pod 'Cosmos'
pod 'MBProgressHUD'

pod 'MJRefresh'
end
